import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CustomProvider from "../customStoreProvider";
import { AppbarClient } from "../components/AppbarClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
          <CustomProvider>
          <body className={inter.className}>
            <AppbarClient/>
            {children}
            </body>
          </CustomProvider>
    </html>
  );
}
